_core:
  default_config_hash: QfRxCsHzZ8_TOqax9jYAfQvj5Kq9Ve7vl4pVziKemhA
source_lang: en
widget_look: flags
url_structure: none
flag_size: '24'
flag_style: 2d
globe_size: '60'
color_scheme: light
alt_flags:
  usa: 0
  canada: 0
  mexico: 0
  argentina: 0
  colombia: 0
  brazil: 0
  quebec: 0
wrapper_selector: .gtranslate_wrapper
float_position: bottom-left
float_switcher_open_direction: top
position: inline
switcher_open_direction: bottom
native_language_names: 1
detect_browser_language: 0
enable_cdn: 1
add_new_line: 1
select_language_label: 'Select Language'
custom_domains: 0
custom_domains_config: ''
custom_css: ''
languages:
  en: en
  it: it
  ru: ru
  es: es
flag_languages:
  en: en
