schemas:
  bootstrap: 8000
  legacy: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://www.pinkfloydlegacy.com/themes/custom/legacy/favicon.ico'
  use_default: 1
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: ''
  url: ''
  use_default: 1
fluid_container: 1
table_responsive: '-1'
breadcrumb: '0'
region_wells:
  header_top_left: ''
  header_top_middle: ''
  header_top_right: ''
  header_bottom: ''
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: well
  footer: ''
  sub_footer_left: ''
  sub_footer_right: ''
  sub_footer_middle: ''
cdn_theme: bootstrap
cdn_cache_ttl_versions: '604800'
cdn_cache_ttl_themes: '604800'
cdn_cache_ttl_assets: '0'
cdn_cache_ttl_library: '0'
reset_http_request_cache: ''
table: ''
